---
- hostname: csw1
  p2p_wan1: x.x.x.x1
  p2p_wan2: x.x.x.x9
  vlan20_csw_ip: x.x.0.2
  vlan20_gw_ip: x.x.0.1
  vlan30_csw_ip: x.x.0.2
  vlan30_gw_ip: x.x.0.1
  csw_to_csw: x.x.x.x21

- hostname: csw2
  p2p_wan1: x.x.x.x6
  p2p_wan2: x.x.x.x13
  vlan20_csw_ip: x.x.0.3
  vlan20_gw_ip: x.x.0.1
  vlan30_csw_ip: x.x.0.3
  vlan30_gw_ip: x.x.0.1
  csw_to_csw: x.x.x.x22
