devices:
  - name: csw1
    hostname: csw1
    p2p_wan1: GigabitEthernet1
    p2p_wan2: Connection to ISP
    vlan20_csw_ip: x.x.x.x
    vlan20_gw_ip: x.x.x.x
    vlan30_csw_ip: x.x.x.x
    vlan30_gw_ip: x.x.x.x
    csw_to_csw: x.x.x.x

  - name: csw2
    hostname: csw2
    p2p_wan1: GigabitEthernet1
    p2p_wan2: Connection to ISP
    vlan20_csw_ip: x.x.x.x
    vlan20_gw_ip: x.x.x.x
    vlan30_csw_ip: x.x.x.x
    vlan30_gw_ip: x.x.x.x
    csw_to_csw: x.x.x.x
  
  # - name: asw1
  #   hostname: asw1
  
  # - name: asw2
  #   hostname: asw2