devices:
  - name: csw1
    hostname: csw1
    p2p_wan1: GigabitEthernet1
    p2p_wan2: Connection to ISP
    vlan20_csw_ip: 10.120.0.2
    vlan20_gw_ip: 10.120.0.1
    vlan30_csw_ip: 10.121.0.2
    vlan30_gw_ip: 10.120.0.1
    csw_to_csw: 20.20.20.21

  - name: csw2
    hostname: csw2
    p2p_wan1: GigabitEthernet1
    p2p_wan2: Connection to ISP
    vlan20_csw_ip: 10.120.0.2
    vlan20_gw_ip: 10.120.0.1
    vlan30_csw_ip: 10.121.0.2
    vlan30_gw_ip: 10.120.0.1
    csw_to_csw: 20.20.20.21
  
  # - name: asw1
  #   hostname: asw1
  
  # - name: asw2
  #   hostname: asw2